[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.84"
common = { path = "../common", default-features = false }

[features]
default = ["std"]
std = [
    "common/std",
]
